#define THERMISTOR_ATTACHED_RESISTOR_VAL 1000

#define TEMPERATURE_UPDATE_TIME 1000
#define TEMPERATURE_SAMPLES 10
#define TEMPERATURE_TOLERANCE_PERCENTAGE 50
#define TEMP_INDICATOR_PATIENCE 500
#define TEMP_HALT_PATIENCE 10000
#define PIXEL_UPDATE_PATIENCE 800

#define COMPRESSOR_MIN_TEMP 10
#define COMPRESSOR_MAX_TEMP 28
#define COMPRESSOR_EXTREME_HIGH_TEMP 40
#define COMPRESSOR_EXTREME_LOW_TEMP -10
#define COMPRESSOR_STOP_TEMP 13
#define COMPRESSOR_START_TEMP 15

#define COMPRESSOR_HP_ALERT_PATIENCE 5000
#define COMPRESSOR_LP_ALERT_PATIENCE 10000
#define COMPRESSOR_LP_HALT_PATIENCE 15000
#define TEMPERATURE_READING_PATIENCE 10000

#define BUTTON_PRESS_RELEASE_DELAY 30

#define FLOW_PATIENCE 6000
#define RESET_PATIENCE 2000
#define START_PATIENCE 20
#define STOP_PATIENCE 80
#define COMPRESSOR_BLINK_DURATION 5000
#define COMPRESSOR_BLINK_RATE 1000

#define AD_TIME 2000

char DEGREE_SYMBOL = '°';
